-- V1.1: Criação das tabelas do sistema Mottu (após baseline)
-- Esta migração cria todas as tabelas necessárias

-- Tabela de usuários
CREATE TABLE usuario (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR2(50) NOT NULL UNIQUE,
    senha VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'USER' NOT NULL
);

-- Tabela de grupos de status
CREATE TABLE status_grupo (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL
);

-- Tabela de status
CREATE TABLE status (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    status_grupo_id NUMBER(19),
    CONSTRAINT fk_status_grupo FOREIGN KEY (status_grupo_id) REFERENCES status_grupo(id)
);

-- Tabela de zonas
CREATE TABLE zona (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    letra VARCHAR2(1) NOT NULL
);

-- Tabela de pátios
CREATE TABLE patio (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL
);

-- Tabela de motos
CREATE TABLE moto (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR2(10),
    chassi VARCHAR2(50),
    qr_code VARCHAR2(100),
    data_entrada TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    previsao_entrega TIMESTAMP,
    fotos VARCHAR2(500),
    observacoes VARCHAR2(1000),
    zona_id NUMBER(19),
    patio_id NUMBER(19),
    status_id NUMBER(19),
    CONSTRAINT fk_moto_zona FOREIGN KEY (zona_id) REFERENCES zona(id),
    CONSTRAINT fk_moto_patio FOREIGN KEY (patio_id) REFERENCES patio(id),
    CONSTRAINT fk_moto_status FOREIGN KEY (status_id) REFERENCES status(id)
);

-- Índices para melhor performance
CREATE INDEX idx_moto_placa ON moto(placa);
CREATE INDEX idx_moto_chassi ON moto(chassi);
CREATE INDEX idx_moto_qr_code ON moto(qr_code);
CREATE INDEX idx_moto_data_entrada ON moto(data_entrada);
