-- V1.1: Criação das tabelas do sistema Mottu (após baseline)
-- Esta migração cria todas as tabelas necessárias (idempotente)

-- Tabela de usuários
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE usuario (
        id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        usuario VARCHAR2(50) NOT NULL UNIQUE,
        senha VARCHAR2(255) NOT NULL,
        role VARCHAR2(20) DEFAULT ''USER'' NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -54, -2264, -2260) THEN NULL; -- Objeto já existe ou recurso ocupado
        ELSE RAISE;
        END IF;
END;
/

-- Tabela de grupos de status
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE status_grupo (
        id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(100) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -54, -2264, -2260) THEN NULL; -- Objeto já existe ou recurso ocupado
        ELSE RAISE;
        END IF;
END;
/

-- Tabela de status
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE status (
        id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(100) NOT NULL,
        status_grupo_id NUMBER(19),
        CONSTRAINT fk_status_grupo FOREIGN KEY (status_grupo_id) REFERENCES status_grupo(id)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -54, -2264, -2260) THEN NULL; -- Objeto já existe ou recurso ocupado
        ELSE RAISE;
        END IF;
END;
/

-- Tabela de zonas
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE zona (
        id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(100) NOT NULL,
        letra VARCHAR2(1) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -54, -2264, -2260) THEN NULL; -- Objeto já existe ou recurso ocupado
        ELSE RAISE;
        END IF;
END;
/

-- Tabela de pátios
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE patio (
        id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome VARCHAR2(100) NOT NULL
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -54, -2264, -2260) THEN NULL; -- Objeto já existe ou recurso ocupado
        ELSE RAISE;
        END IF;
END;
/

-- Tabela de motos
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE moto (
        id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        placa VARCHAR2(10),
        chassi VARCHAR2(50),
        qr_code VARCHAR2(100),
        data_entrada TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        previsao_entrega TIMESTAMP,
        fotos VARCHAR2(500),
        observacoes VARCHAR2(1000),
        zona_id NUMBER(19),
        patio_id NUMBER(19),
        status_id NUMBER(19),
        CONSTRAINT fk_moto_zona FOREIGN KEY (zona_id) REFERENCES zona(id),
        CONSTRAINT fk_moto_patio FOREIGN KEY (patio_id) REFERENCES patio(id),
        CONSTRAINT fk_moto_status FOREIGN KEY (status_id) REFERENCES status(id)
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -54, -2264, -2260) THEN NULL; -- Tabela/constraint já existe ou recurso ocupado
        ELSE RAISE;
        END IF;
END;
/

-- Índices para melhor performance
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_moto_placa ON moto(placa)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -54, -2264, -2260) THEN NULL; -- Índice já existe ou recurso ocupado
        ELSE RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_moto_chassi ON moto(chassi)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -54, -2264, -2260) THEN NULL; -- Índice já existe ou recurso ocupado
        ELSE RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_moto_qr_code ON moto(qr_code)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -54, -2264, -2260) THEN NULL; -- Índice já existe ou recurso ocupado
        ELSE RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_moto_data_entrada ON moto(data_entrada)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -54, -2264, -2260) THEN NULL; -- Índice já existe ou recurso ocupado
        ELSE RAISE;
        END IF;
END;
/
